### ISSUE TITLE
Fine tuning french BERT model on my own dataset for summarization task

### ISSUE THREAD

**Issue by Ghani-25** [poloclub/dodrio#1]
Hello,

firstly I want to congratulate you for your brilliant work.  I have a question, I am working on text summarization project and my own dataset is in french, is it possible to use Dodrio's visualizations?  if so, what needs to be changed?
 Thank you

**Comment by xiaohk** [comment]
Hello, thanks for your interest in Dodrio!

Sure thing, Dodrio can help you visualize the attention weights in a fine-tuned French BERT model. Dodrio is a web-based system and it uses pre-computed data files (JSON files) to populate the visualizations. You can see a list of all the data files Dodrio's public demo is using:

https://github.com/poloclub/dodrio/blob/458c40513f5aef6879fb9b5bab1ce9348ab124c7/src/Main.svelte#L17-L25

These JSON files are included in the [`public/data`](https://github.com/poloclub/dodrio/tree/master/public/data) folder.

Dodrio relies on three types of extracted data from your dataset and model. You can learn more about it from [our paper](http://arxiv.org/abs/2103.14625):

1. Semantic information (human annotation or saliency score)
2. Syntactic information (human annotation or parsed syntactic dependencies)
3. Importance score (confidence score, sum of absolute attention gradients, or [LRP](https://arxiv.org/pdf/1905.09418.pdf), etc.)

Therefore, you want to extract and generate JSON files with the same data structure from your dataset and model. To make the process easier, we provide a Python [script](https://github.com/poloclub/dodrio/blob/master/data-generation/dodrio-data-gen.py) and its detailed [documentation](https://github.com/poloclub/dodrio/tree/master/data-generation) to demonstrate how to generate all required JSON files. You should definitely check them out :)

We are very excited to see how Dodrio can be used in more languages and tasks, and we are more than happy to help you visualize your model with Dodrio. Let us know if you have any questions along the way 🤗

**Comment by xiaohk** [comment]
Hopefully https://github.com/poloclub/dodrio/issues/1#issuecomment-814400264 helps you visualize your BERT model with French dataset! I will close the issue now, feel free to re-open it if you have more questions :)
