### ISSUE TITLE
Can it be modified to visualize Attention in Computer Vision?

### ISSUE THREAD

**Issue by jyang68sh** [poloclub/dodrio#3]
Hi, Thanks for the amazing work!

Personally, I focus more on CV field. So, I would like to know if this tool can also be used to visualize Attention in CV.

**Comment by xiaohk** [comment]
Thanks! We are glad that you enjoy this tool :)

Dodrio is designed for language models with attention mechanisms. I imagine that one needs to modify the tool a lot to fit vision models with mechanisms. For example, one main feature in Dodrio is to distinguish and analyze the effects of different attention heads (semantic vs. syntactic). Users can easily compare the syntactic dependencies predicted using attention weights and the ground truth dependencies. It is probably harder to do in a CV model where we don't really know the "dependencies/syntax" between different pixels.

However, I believe the attention head map view can be helpful for CV models too, where users can visually compare attention heads across layers. We have some interests in extending Dodrio to CV models with attention mechanisms. We will let you know if we have more update! I will close the issue now, feel free to re-open it if you have more questions :)

**Comment by jyang68sh** [comment]
@xiaohk Thanks for your quick replay. I would like to contribute it if you guys decided to extend Dodrio to CV models. Please let me know!
