### ISSUE TITLE
Issue when attempting to visualize custom dataset

### ISSUE THREAD

**Issue by Fquico1999** [poloclub/dodrio#4]
Hi, 
I've followed the steps provided in `dodrio-data-gen.py` and have generated the JSON files as required. 
![image](https://user-images.githubusercontent.com/30972195/144728596-471b75fb-3ce7-4428-bb91-d5dba30a2524.png)

I have then added them to `public/data` and updated `src/Main.svelte` to reflect the proper files.
![image](https://user-images.githubusercontent.com/30972195/144728619-a84b9be5-7019-4259-a730-c4f9275fe31f.png)

However, when I run `npm run dev`, the result is blank, the user interface is all there, but there are no visualizations.
![image](https://user-images.githubusercontent.com/30972195/144728640-17ad856a-1605-4f49-b2ff-47f4da4e758c.png)
I can see, however, that the instance selection shows elements of the correct dataset. 

Any tips on how to fix this?

**Comment by xiaohk** [comment]
Hi @Fquico1999, thanks for trying out Dodrio!

Do you get any error in the browser console? 

For example, if you use chrome, you can open the web console by following these [instructions](https://developer.chrome.com/docs/devtools/open/).

**Comment by Fquico1999** [comment]
Yes, @xiaohk I do see some errors, 
![image](https://user-images.githubusercontent.com/30972195/144801880-14eaa2ff-9130-47b7-afa1-d23d14c4950f.png)
Im not very experienced with js or d3, so I'll attempt to debug and report here with any results.
In the meantime, if you have any ideas what this could be, please let me know

**Comment by xiaohk** [comment]
It seems one of the data variables (`headOrderMap.syntactic`, `headOrderMap.semantic `, or `headOrderMap.important`) is not initialized (`undefined`). You can try to print out these variables in before the error line, e.g. `console.log(headOrderMap)`.

Good luck! Keep us updated.

https://github.com/poloclub/dodrio/blob/9da674b273412a14844cee894b7cfd8683e805f4/src/dependency-view/Dependency.svelte#L724-L762

**Comment by Fquico1999** [comment]
@xiaohk It seems like the problem arises when trying to access the index `instanceID`. Since my dataset has less elements than 1562, it returns undefined for several parameters. 
I've seen references and definitions of `instanceID` in several locations, where would be the best place to change it?

**Comment by Fquico1999** [comment]
Got it working!
![image](https://user-images.githubusercontent.com/30972195/144935482-fd186727-d387-4a0b-9fc1-ccbb3d4312fe.png)

The problem was the one describe above, `instanceID` is defined in several files to be 1562, and needs to be changed to an index that exists in the dataset. Once that was changed, it seems to work.

I believe it would be useful to have `instanceID` defined in a single accessible location. Or if that is not possible, then perhaps changing it to `1` under the assumption that most datasets are at least length 1.
