### ISSUE TITLE
Change hardcoded InstanceID definition in several files

### ISSUE THREAD

**Issue by Fquico1999** [poloclub/dodrio#5]
As referenced in #4 , I had an issue when trying to visualize a custom dataset that had less entries than the default `instanceID=1562`.
This value is defined in several different files.
I suggest making this easier to set, setting it to `1`, or mentioning the need to change this value in `dodrio-data-gen.py` and its README.

**Comment by xiaohk** [comment]
Sorry for the late reply. Thank you so much @Fquico1999!! Nice catch. I have updated the README file.
