### ISSUE TITLE
problems

### ISSUE THREAD

**Issue by Danny-C-Auditore** [poloclub/dodrio#6]
sorry to disturb, I don't have a clue to open and run it.....could you tell me by which way? pycharm? 
I am working on an article on machine translate, needing the dodrio to provide me a visual access to the mechanism during the process of transformer model and I want to change the input into the sentences chosen by myself, but the online demo version seems not able to. 
thank you greatly.

**Comment by xiaohk** [comment]
Thank you so much for trying out Dodrio!

Dodrio is a web-based tool. You can first download this repository to your local machine (or `git clone`). After [installing npm](https://docs.npmjs.com/downloading-and-installing-node-js-and-npm), you can run the following commands in the terminal:

```bash
npm install
npm run dev
```
Use a web browser to open [localhost:5000](https://localhost:5000/), and you will see Dodrio running there :)

To see how we trained the Transformer or customize the visualization with a different model or dataset, visit the [./data-generation/](https://github.com/poloclub/dodrio/blob/master/data-generation) directory. You can also see https://github.com/poloclub/dodrio/issues/4 for more information on using Dodrio for customized model/dataset.

**Comment by Danny-C-Auditore** [comment]
Firstly, I have successfully run your demo on my device, I appreciate your favor greatly.  But I have encountered another one.
I have had all the packages install on my device, however, it still warns. I want to know what is the "modeling_bert" for? isn't it included in the transformers? And, the package "datasets" ,how can I get it?

Thank you!
![image](https://user-images.githubusercontent.com/66711049/160774436-3f142f4a-3097-42ca-b1c1-959952834e86.png)

**Comment by xiaohk** [comment]
Hello. The "modeling_bert" comes from the transformer package. You should be able to import it if you run `pip install transformers` (https://github.com/huggingface/transformers).

The "datasets" is also a huggingface package. You can install it by `pip install datasets` (https://github.com/huggingface/datasets)

**Comment by Danny-C-Auditore** [comment]
hi, @xiaohk ,actually I had the "transformers" installed before, and tested well in a test.py file,  while it still didn't work out in 
dodrio-data-gen.py.  
I wonder if there is any requirements for the version of the transformers, since I didn't find any subfile named "modeling_bert", and my version of transformers is 4.17.0
apology for disturbance, again. Thanks for your patience.

**Comment by Danny-C-Auditore** [comment]
thanks, I have solved the problems by finding the right path " transformers.models.bert.modeling_bert " 
@xiaohk

**Comment by xiaohk** [comment]
No problem. Good luck with your project. Let me know if you have more questions.
